# Generated by Django 5.1.1 on 2024-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=10000),
        ),
    ]
